version: "3"
services:
  backend:
    container_name: backend
    build:
      context: .
    volumes:
      - .:/app
    networks:
      - concrete-net
    ports:
      - 8081:8080

networks:
  concrete-net:
    external: true
